spring:
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:mongodb://localhost:27017
  application:
    name: book-service
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 8886

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
